-- =====================================================================
-- 15_post_setup.sql        (run as COLLEGE after 01-13)
-- Fills the calculated tables so the demo opens with real results and payroll:
--   * RESULT   : calculated from the raw MARKS by the stored procedure
--   * PAYROLL  : September 2026 generated by the stored procedure
-- Then clears AUDIT_LOG so that the audit screen starts empty for the demo.
-- =====================================================================
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_results NUMBER;
  v_payroll NUMBER;
BEGIN
  calculate_all_results(v_results);
  generate_payroll_all('2026-09', v_payroll);
  DBMS_OUTPUT.PUT_LINE('Results calculated : ' || v_results);
  DBMS_OUTPUT.PUT_LINE('Payroll rows created: ' || v_payroll);
END;
/

DELETE FROM audit_log;
COMMIT;

PROMPT === 15_post_setup.sql finished ===
